name: snowintel
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python==3.09
  - geopandas
  - jupyter
  - numpy
  - xarray
  - pandas
  - fastparquet
  - pre-commit
  - pytest
  - xmltodict
  - zeep
  - pip
  - pip:
      - -e .
