name: snowintel
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.9
  - geopandas
  - jupyter
  - numpy
  - xarray
  - pandas
  - fastparquet
  - folium
  - pre-commit
  - pytest
  - pydata-sphinx-theme
  - sphinx
  - xmltodict
  - zeep
  - pip
  - pip:
      - -e .
